{
  "openapi": "3.0.3",
  "info": {
    "title": "The PEAS Procedure Data service API",
    "version": "0.1-SNAPSHOT",
    "description": "HTTP API to PEAS Data service, used for storing and retrieving PEAS procedure run data"
  },
  "paths": {
      
     "/createNewProcedureRun": {
      "post": {
        "description": "Creates a new procedure run record in the APS-PEAS database",
        "operationId": "postCreateNewProcedureRun",
        "responses": {
          "200": {
            "description": "Returns the ID of the new procedure run",
            "content": {
              "application/json": {
                "schema": {
                  "type": "integer",
                  "example": 1234
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },

    "/storeProcedureSetupData": {
      "post": {
        "description": "Stores one set of setup data for an alignment procedure iteration",
        "operationId": "postStoreProcedureSetupData",
        "requestBody": {
          "description": "Stores one set of setup data for an alignment procedure iteration in cache and APS-PEAS database.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProcedureSetupData"
              },
              "example": {
                "procedureRunId": "1234",
                "iterationIndex": "0",
                "pairs": [
                  { "key": "someKey", "type": "string", "value": "xq345" },
                  { "key": "someOtherKey", "type": "integer", "value": "15" }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },
    "/storeAsRunProcedureConfiguration": {
      "post": {
        "description": "Stores as-run procedure configuration in cache and APS-PEAS database",
        "operationId": "postStoreAsRunProcedureConfiguration",
        "requestBody": {
          "description": "Stores as-run procedure configuration in cache and APS-PEAS database",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProcedureAsRunConfigurationData"
              },
              "example": {
                "procedureRunId": "1234",
                "keyValuePairs": [
                  { "key": "someKey", "type": "string", "value": "xq345" },
                  { "key": "someOtherKey", "type": "integer", "value": "15" }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },

    "/storeProcedureComputationResults": {
      "post": {
        "description": "Stores a computation result set in cache and in APS-PEAS database",
        "operationId": "postStoreProcedureComputationResults",
        "requestBody": {
          "description": "Stores a computation result set in cache and in APS-PEAS database.  For multi-dimensional data, dim1 is the fastest changing index and is used for 1-D vector lengths.  When both dim1 and dim2 are zero, the value is a scalar",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProcedureComputationResults"
              },
              "example": {
                "procedureRunId": "1234",
                "exposureNum": "3", 
                "computationName": "FindCent",
                "keyValuePairs": [
                  { "key": "scalarValue", "type": "float", "dim1": 0, "dim2": 0, "value": "23.4" },
                  { "key": "stringValue", "type": "string", "dim1": 0, "dim2": 0, "value": "a string" },
                  { "key": "twoDimValue",  "type": "float", "dim1": 2, "dim2": 3, "value": "{{14.5, 23.3}, {43.2, 456.3}, {12.0, 0.9}}" }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },
      
    "/storePeasNotificationEvent": {
      "post": {
        "description": "Stores a PEAS notification event message in cache and APS-PEAS database.",
        "operationId": "postStorePeasNotificationEvent",
        "requestBody": {
          "description": "Stores notification event message in cache and APS-PEAS database.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PeasNotificationEvent"
              },
              "example": {
                "procedureRunId": "1234",
                "timestamp": "2045-02-23 11:23:35", 
                "severity": "Info",
                "message": "An informational message"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },
      
    "/setProcedureRunCompletionStatus": {
      "post": {
        "description": "Stores the procedure run completion status (Success|Aborted) in the APS-PEAS database.",
        "operationId": "postSetProcedureRunCompletionStatus",
        "requestBody": {
          "description": "Stores the procedure run completion status (Success|Aborted) in the APS-PEAS database.",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["completionStatus"],
                "properties": {
                  "completionStatus": {
                    "type": "string",
                    "description": "the completion status",
                    "enum": ["success", "aborted"]
                  }
                }
              },
              "example": {
                "completionStatus": "success"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },
     
    "/storeCentroidMap": {
      "post": {
        "description": "Stores a centroid map for an exposure in the APS-PEAS database.",
        "operationId": "postStoreCentroidMap",
        "requestBody": {
          "description": "Stores a centroid map for an exposure in the APS-PEAS database.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CentroidMapData"
              },
              "example": {
                "procedureRunId": "1234",
                "exposureTimestamp": "2045-02-23 11:23:35",
                "iterationNumber": 1,
                "centroidList": [
                  { "xValue": 107.4, "yValue": 2301.4 },
                  { "xValue": 560.0, "yValue": 345.9 },
                  { "xValue": 2561.3, "yValue": 4723.4 }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },
 
    "/getRemainingSpace": {
      "get": {
        "description": "Gets the remaining space on the APS Shared disk.",
        "operationId": "getRemainingSpace",
        "parameters": [
        ],

        "responses": {
          "200": {
            "description": "Remaining space in MB",
            "content": {
              "application/json": {
                "schema": {
                  "type": "integer"
                },
                "example": "5436"
              }
            }
          },
          "400": {
            "description": "Bad Request.  Arguments provided were not correct or were incomplete",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    } 
      
      
      
  },
  "components": {
    "schemas": {
      "NameValuePair": {
        "required": [
          "key",
          "type",
          "dim1",
          "dim2",
          "encodedStringValue"
        ],
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "dim1": {
            "type": "integer"
          },
          "dim2": {
            "type": "integer"
          },
          "encodedStringValue": {
            "type": "string"
          }
        }
      },
      "NameValuePairList": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/NameValuePair"
        }
      },
      "ProcedureSetupData": {
        "required": [
          "keyValuePairs",
          "iterationIndex",
          "procedureRunId"
        ],
        "type": "object",
        "properties": {
          "procedureRunId": {
            "type": "integer"
          },
          "iterationIndex": {
            "type": "integer"
          },
          "keyValuePairs": {
            "$ref": "#/components/schemas/NameValuePairList"
          }
        }
      },
      "ProcedureComputationResults": {
        "required": [
          "keyValuePairs",
          "procedureRunId", 
          "exposureNum",
          "computationName"
        ],
        "type": "object",
        "properties": {
          "procedureRunId": {
            "type": "integer"
          },
          "exposureNum": {
            "type": "integer"
          },
          "computationName": {
            "type": "string"
          },
          "keyValuePairs": {
            "$ref": "#/components/schemas/NameValuePairList"
          }
        }
      },
      "ProcedureAsRunConfigurationData": {
        "required": [
          "keyValuePairs",
          "procedureRunId"
        ],
        "type": "object",
        "properties": {
          "procedureRunId": {
            "type": "integer"
          },
          "keyValuePairs": {
            "$ref": "#/components/schemas/NameValuePairList"
          }
        }
      },
       "PeasNotificationEvent": {
        "required": [
          "procedureRunId",
          "timestamp", 
          "severity",
          "message"
        ],
        "type": "object",
        "properties": {
          "procedureRunId": {
            "type": "integer"
          },
          "timestamp": {
            "type": "date-time"
          },
          "severity": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        }
      },
    
        
        
        
      "Centroid": {
        "required": [
          "xValue",
          "yValue"
        ],
        "type": "object",
        "properties": {
          "xValue": {
            "type": "float"
          },
          "yValue": {
            "type": "float"
          }
        }
      },
      "CentroidList": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Centroid"
        }
      },
  
      "CentroidMapData": {
        "required": [
          "procedureRunId",
          "iterationNumber",
          "exposureNumber",
          "centroidList"
        ],
        "type": "object",
        "properties": {
          "procedureRunId": {
            "type": "integer"
          },
          "iterationNumber": {
            "type": "integer"
          },
          "exposureNumber": {
            "type": "integer"
          },
          "centroidList": {
            "$ref": "#/components/schemas/CentroidList"
          }
        }
      },
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
      "QueryResult": {
        "required": [
          "apsFilename",
          "uri",
          "loRezUri"
        ],
        "type": "object",
        "properties": {
          "exposureId": {
            "type": "string",
            "description": "the exposure Id of the PSH exposure"
          },
          "apsFilename": {
            "type": "string",
            "description": "the APS filename of the PSH exposure"
          },
          "uri": {
            "type": "string",
            "description": "the uri to access the exposure"
          },
          "loRezUri": {
            "type": "string",
            "description": "the uri to access the low-rez exposure image file"
          }
        }
      },
      "Exposure": {
        "required": [
          "utc",
          "det"
        ],
        "type": "object",
        "properties": {
          "utc": {
            "type": "string",
            "description": "date and time of exposure yyyy-mm-dd hh:mm:ss",
            "format": "datetime"
          },
          "det": {
            "type": "string",
            "description": "detector"
          },
          "procType": {
            "type": "string",
            "description": "procedure type"
          },
          "procNum": {
            "type": "string",
            "description": "procedure run number within a night session"
          },
          "expNum": {
            "type": "string",
            "description": "exposure number within a procedure run"
          },
          "mask": {
            "type": "string",
            "description": "pupil mask"
          }
        }
      }
    }
  }
}

}