{
  "openapi": "3.0.3",
  "info": {
    "title": "The PEAS Exposure service API",
    "version": "0.1-SNAPSHOT",
    "description": "HTTP API to PEAS Exposure service, used for keeping track of PEAS exposures and compressed format images"
  },
  "paths": {
      
    "/generateLoRezImage": {
      "post": {
        "description": "Generates a low-resolution .png image from an exposure",
        "operationId": "postGenerateLoRezImage",
        "requestBody": {
          "description": "Requests the exposure service to generate and store a low resolution image from an exposure.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Exposure"
              },
              "example": {
                "utc": "2021-05-27 12:20:13",
                "det": "PSH",
                "procType": "BBP", 
                "procNum" : "14",
                "expNum" : "9",
                "mask" : "PH-2-0"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },

 
 
    "/queryPshExposureFiles": {
      "get": {
       "description": "Queries the APS-PEAS database for Primary Shack-Hartmann exposure Ids given the filter criteria.  Returns PSH exposure ids and APS FITS filesname for the search criteria.",
        "operationId": "getPshExposures",
        "parameters": [
          {
            "name": "nightSessionId",
            "in": "query",
            "description": "the night session id for the night the exposure was taken",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": "1234"
          },
          {
            "name": "procedureType",
            "in": "query",
            "description": "The procedure name: e.g. Coarse Tilt Alignment, Narrowband Phasing",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "Narrowband Phasing"
          },
          {
            "name": "startDateRange",
            "in": "query",
            "description": "The start date range to filter results",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "2025-04-03"
          },
          {
            "name": "endDateRange",
            "in": "query",
            "description": "The end date range to filter results",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "2025-04-03"
          },
          {
            "name": "procedureRunId",
            "in": "query",
            "description": "The procedure run id for the procedure run the exposure was taken in",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": "1234"
          },
          {
            "name": "procedureRunExposureNumber",
            "in": "query",
            "description": "The exposure number within the procedure run",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": "1234"
          },
          {
            "name": "filter",
            "in": "query",
            "description": "The PSH filter used for the exposure",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "F750W"
          },
          {
            "name": "pupilMask",
            "in": "query",
            "description": "The PSH pupilMask used for the exposure",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "PH-2-0"
          },
          {
            "name": "usedForAnalysis",
            "in": "query",
            "description": "Filter exposures that were or were not used in analysis",
            "required": false,
            "schema": {
              "type": "boolean"
            },
            "example": "true"
          }
        ],
        "responses": {
          "200": {
            "description": "A list of exposure Ids and correspoding FITS filenames in APS format",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/QueryResult"
                  }
                },
                "example": [
                  {
                    "exposureId": "2021-05-27_rest_tbd",
                    "apsFilename": "2021-05-27_09:06:56_PSH_BBP_14_09_PH-2-0",
                    "uri": "file:///APSShare/PSH/2021-05-27_09:06:56_PSH_BBP_14_09_PH-2-0.FITS",  
                    "loRezUri": "file:///APSShare/PSH/2021-05-27_09:06:56_PSH_BBP_14_09_PH-2-0.png"  
                  }
                ]
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },
      
    "/queryPitFiles": {
      "get": {
        "description": "Queries the APS-PEAS database for PIT files given the filter criteria.",
        "operationId": "getPitFiles",
        "parameters": [
          {
            "name": "startDateRange",
            "in": "query",
            "description": "The start date range to filter results",
            "required": false,
            "schema": {
              "type": "date"
            },
            "example": "2025-04-03"
          },
          {
            "name": "endDateRange",
            "in": "query",
            "description": "The end date range to filter results",
            "required": false,
            "schema": {
              "type": "date"
            },
            "example": "2025-04-03"
          },
          {
            "name": "procedureRunId",
            "in": "query",
            "description": "The procedure run id for the procedure run the exposure was taken in",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": "1234"
          },
          {
            "name": "filter",
            "in": "query",
            "description": "The PIT filter used for the exposure",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "F750W"
          },
          {
            "name": "pupilMask",
            "in": "query",
            "description": "The PIT pupilMask used for the exposure",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "PH-2-0"
          }
        ],

        "responses": {
          "200": {
            "description": "A list of APS PIT exposure filenames",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/QueryResult"
                  }
                },
                "example": [
                  {
                    "exposureId": "",
                    "apsFilename": "2021-05-27_09:06:56_PIT_PH-2-0",
                    "uri": "file:///APSShare/PIT/22021-05-27_09:06:56_PIT_PH-2-0.FITS",  
                    "loRezUri": "file:///APSShare/PIT/2021-05-27_09:06:56_PIT_PH-2-0.png"  
                  }
                ]
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },       
  
    "/queryAptFiles": {
      "get": {
        "description": "Queries the APS-PEAS database for APT files given the filter criteria.",
        "operationId": "getAptFiles",
        "parameters": [
          {
            "name": "startDateRange",
            "in": "query",
            "description": "The start date range to filter results",
            "required": false,
            "schema": {
              "type": "date"
            },
            "example": "2025-04-03"
          },
          {
            "name": "endDateRange",
            "in": "query",
            "description": "The end date range to filter results",
            "required": false,
            "schema": {
              "type": "date"
            },
            "example": "2025-04-03"
          },
          {
            "name": "procedureRunId",
            "in": "query",
            "description": "The procedure run id for the procedure run the exposure was taken in",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": "1234"
          },
          {
            "name": "filter",
            "in": "query",
            "description": "The PIT filter used for the exposure",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "F750W"
          }
        ],

        "responses": {
          "200": {
            "description": "A list of APS APT exposure filenames",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/QueryResult"
                  }
                },
                "example": [
                  {
                    "exposureId": "",
                    "apsFilename": "2021-05-27_09:06:56_APT",
                    "uri": "file:///APSShare/PIT/22021-05-27_09:06:56_APT.FITS",  
                    "loRezUri": "file:///APSShare/PIT/2021-05-27_09:06:56_APT.png"  
                  }
                ]
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },          

    "/queryManualExposureFiles": {
      "get": {
        "description": "Queries the APS-PEAS database for manually taken exposure files given the filter criteria.",
        "operationId": "getManualExposureFiles",
        "parameters": [
          {
            "name": "startDateRange",
            "in": "query",
            "description": "The start date range to filter results",
            "required": false,
            "schema": {
              "type": "date"
            },
            "example": "2025-04-03"
          },
          {
            "name": "endDateRange",
            "in": "query",
            "description": "The end date range to filter results",
            "required": false,
            "schema": {
              "type": "date"
            },
            "example": "2025-04-03"
          },
          {
            "name": "detector",
            "in": "query",
            "description": "The detector the exposure was taken in",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": "1234"
          },
          {
            "name": "filter",
            "in": "query",
            "description": "The filter used for the exposure",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "F750W"
          },
          {
            "name": "pupilMask",
            "in": "query",
            "description": "The pupil mask used for the exposure",
            "required": false,
            "schema": {
              "type": "string"
            },
            "example": "PH-2-0"
          }
        ],

        "responses": {
          "200": {
            "description": "A list of APS manual exposure filenames",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/QueryResult"
                  }
                },
                "example": [
                  {
                    "exposureId": "",
                    "apsFilename": "2021-05-27_09:06:56_APT",
                    "uri": "file:///APSShare/Manual/22021-05-27_09:06:56_APT.FITS",  
                    "loRezUri": "file:///APSShare/Manual/2021-05-27_09:06:56_APT.png"  
                  }
                ]
              }
            }
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },           
    "/retrieveFitsFile": {
      "get": {
        "description": "Retrieves the FITS file data from APS shared disk or if not present, retrieves from DMS.ENG ancillary file store.",
        "operationId": "retriveFitsFile",
        "parameters": [
          {
            "name": "apsFilename",
            "in": "query",
            "description": "The APS filename",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "12-31-2034_11:59:59_PSH_F750W_PH-2-0"
          }            
        ],

        "responses": {
          "200": {
            "description": "File is located and returned successfully",
            "content": {
              "application/octet-stream": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                },
                "example": "opaque file returned"
              }
            }
          },
          "400": {
            "description": "Bad Request.  Arguments provided were not correct or were incomplete",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          },
          "404": {
            "description": "No file was found with the provided URI",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },     
    "/retrieveLowResImage": {
      "get": {
        "description": "Retrieves the low resolution (png or equivalent) image format file data for the given PSH or PIT FITS image.  Creates the low resolution image if it does not exist. If the FTS file is not on the APS shared disk, it is retrieved from the DMS.ENG ancillary file store.",
        "operationId": "retriveLowResImage",
        "parameters": [
          {
            "name": "apsFilename",
            "in": "query",
            "description": "The APS filename",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "12-31-2034_11:59:59_PSH_F750W_PH-2-0"
          }            

        ],

        "responses": {
          "200": {
            "description": "File is located and returned successfully",
            "content": {
              "application/octet-stream": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                },
                "example":"opaque file returned"
              }
            }
          },
          "400": {
            "description": "Bad Request.  Arguments provided were not correct or were incomplete",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          },
          "404": {
            "description": "No file was found with the provided URI",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },       
    "/getRemainingSpace": {
      "get": {
        "description": "Gets the remaining space on the APS Shared disk.",
        "operationId": "getRemainingSpace",
        "parameters": [
        ],

        "responses": {
          "200": {
            "description": "Remaining space in MB",
            "content": {
              "application/json": {
                "schema": {
                  "type": "integer"
                },
                "example": "5436"
              }
            }
          },
          "400": {
            "description": "Bad Request.  Arguments provided were not correct or were incomplete",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },           
    "/getPurgeExcludedImages": {
      "get": {
        "description": "Returns the images currently marked as excluded from the purgeApsSharedDisk method.",
        "operationId": "getPurgeExcludedFiles",
        "parameters": [
        ],

        "responses": {
          "200": {
            "description": "Files currently marked as excluded from the purgeApsSharedDisk method.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                      "type": "string"
                  }
                },
                "example": ["2045-12-12_12:23:33_APT_F750W", "12-31-2034_11:59:59_PSH_F750W_PH-2-0"]
              }
            }
          },
          "400": {
            "description": "Bad Request.  Arguments provided were not correct or were incomplete",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },    
    "/setImageAsPurgeExcluded": {
      "post": {
        "description": "Marks the file as excluded from filesystem purge",
        "operationId": "setFileAsPurgeExcluded",
        "requestBody": {
          "description": "Requests the exposure service to mark the image as excluded from filesystem purge.",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "filename": {
                    "type": "string"
                  }
                },
                "required": ["filename"]
              },
              "example": {
                  "filename": "2045-12-12_12:23:33_APT_F750W"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },      
    "/unsetImageAsPurgeExcluded": {
      "post": {
        "description": "Unmarks the file as excluded from filesystem purge",
        "operationId": "unsetFileAsPurgeIncluded",
        "requestBody": {
          "description": "Requests the exposure service to un-mark the image as excluded from filesystem purge.",
           "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "filename": {
                    "type": "string"
                  }
                },
                "required": ["filename"]
              },
              "example": {
                  "filename": "2045-12-12_12:23:33_APT_F750W"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": ""
          },
          "400": {
            "description": "",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Error message."
              }
            }
          }
        }
      }
    },      
    "/purgeApsSharedDisk": {
      "delete": {
        "description": "Deletes files from the APS Shared disk that are older than the specified date and are not marked as excluded.",
        "operationId": "purgeFilesBeforeDate",
        "parameters": [
          {
            "name": "beforeDate",
            "in": "query",
            "required": true,
            "description": "Delete files older than this date (format: YYYY-MM-DD).",
            "schema": {
              "type": "string",
              "format": "date"
            },
            "example": "2045-12-12"
          }
        ],
        "responses": {
          "200": {
            "description": "Files successfully deleted.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "example": ["file1.tmp", "file2.tmp"]
              }
            }
          },
          "400": {
            "description": "Invalid date format or request.",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "example": "Invalid 'beforeDate' format. Expected YYYY-MM-DD."
              }
            }
          }
        }
      }
    }  
  },    

  "components": {
    "schemas": {
      "QueryResult": {
        "required": [
          "apsFilename",
          "uri",
          "loRezUri"
        ],
        "type": "object",
        "properties": {
          "exposureId": {
            "type": "string",
            "description": "the exposure Id of the PSH exposure"
          },
          "apsFilename": {
            "type": "string",
            "description": "the APS filename of the PSH exposure"
          },
          "uri": {
            "type": "string",
            "description": "the uri to access the exposure"
          },
          "loRezUri": {
            "type": "string",
            "description": "the uri to access the low-rez exposure image file"
          }
        }
      },
       "Exposure": {
        "required": [
          "utc", "det"
        ],
        "type": "object",
        "properties": {
          "utc": {
            "type": "string",
            "description": "date and time of exposure yyyy-mm-dd hh:mm:ss",
            "format": "datetime"
          },
          "det": {
            "type": "string",
            "description": "detector"
          },
          "procType": {
            "type": "string",
            "description": "procedure type"
          },
          "procNum": {
            "type": "string",
            "description": "procedure run number within a night session"
          },
          "expNum": {
            "type": "string",
            "description": "exposure number within a procedure run"
          },
          "mask": {
            "type": "string",
            "description": "pupil mask"
          }
        }
      }
    }
  }
}
